DROP TABLE IF EXISTS meters;
DROP TABLE IF EXISTS meter_data;

CREATE TABLE meters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL
);

CREATE TABLE meter_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meter_id INT NOT NULL,
    value INT NOT NULL,
    timestmp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


